name: Upload Website to S3

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      # install dependencies and run unit tests
      - name: Install dependencies and run unit tests
        run: npm install # && npm run test

      - name: Build React App
        run: npm run build # prepend with REACT_APP_API_KEY=${{ secrets.API_KEY }}

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.BUCKET }} --delete
